public class TM_Utils {
    public static final Integer MATCH_RESULT_DRAW = 0;
    public static final Integer MATCH_RESULT_WIN = 1;
    public static final Integer MATCH_RESULT_LOSE = -1;

    public static final String TOURNAMENT_TYPE_CUP = 'Cup';
    public static final String TOURNAMENT_TYPE_CWG = 'Cup (with groups)';
    public static final String TOURNAMENT_TYPE_BR = 'Battle Royale';
    public static final String TOURNAMENT_TYPE_LEAGUE = 'League';
}